name: Build and Deploy to Web

on:
  push:
    branches: [ main, storybook ]
    # for now
    
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        name: Checkout repository
      - uses: subosito/flutter-action@v2.7.1
        with:
          channel: master
        name: Set up Flutter
      - name: Set up Pages
        uses: actions/configure-pages@v1
      - name: Get dependencies
        run: flutter pub get && flutter pub upgrade
        working-directory: ./flutter/example
      - name: Build Zenit UI for Web
        run: flutter build web --release
        working-directory: ./flutter/example
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: flutter
          path: './flutter/example/build/web/'
  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        name: Checkout repository
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x
      - name: Build Storybook
        run: | # Install npm packages and build the Storybook files
          npm ci --dev
          npm run build
          npm run build-storybook
        working-directory: ./storybook
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          path: './storybook/storybook-static'
          name: storybook
  merge-artifacts:
    runs-on: ubuntu-latest
    needs: [build-flutter, build-storybook]
    steps:
      - name: "Download artifacts"
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Copy flutter build into storybook
        run: rsync -av artifacts/flutter artifacts/storybook/flutter
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: './artifacts/storybook'
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: merge-artifacts
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
