
name: Build and Deploy to Web

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
      - name: Switch Flutter channel
        run: flutter channel master
      - name: Make sure Flutter is up to date
        run: flutter upgrade
      - name: Enable Web support
        run: flutter config --enable-web
      - name: Install system dependencies
        run: sudo apt update && sudo apt install cmake ninja-build clang libgtk-3-dev util-linux liblzma-dev libgcrypt-dev -y
      - name: Get dependencies
        run: flutter pub get && flutter pub upgrade
      - name: Build ZenitUI Web preview
        run: flutter build web --release
        working-directory: ./example
      - name: Deploy to GitHub pages
        run: |
          git config user.name github-actions
          git config user.email "action@github.com"
          git --work-tree build/web add --all
          git commit -m "Automatic deployment by github-actions"
          git push origin HEAD:gh-pages --force
