
name: Build and Deploy to Web

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: master
      - name: Get dependencies
        run: flutter pub get && flutter pub upgrade
      - name: Build ZenitUI Web preview
        run: flutter build web --release
        working-directory: ./example
      - name: Deploy to GitHub pages
        run: |
          git config user.name github-actions
          git config user.email "action@github.com"
          git --work-tree example/build/web add --all
          git commit -m "Automatic deployment by github-actions"
          git push origin HEAD:gh-pages --force
